### ISSUE TITLE
qualche dipendenza tra le righe selezionate in tabella (i check button non sembrano indipendenti)

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#1]
Analysis lineage independent
United Kingdom / 2021-12-31 / 4 weeks
Tolgo l'opzione "show important mutations"
Ordino per Y-intercept asc e viene come prima la mut Spike_R346K
Supponiamo che deselezioni tutte le righe che sono selezionate di default e tenga solo le seguenti

![image](https://user-images.githubusercontent.com/11488353/149322141-40617376-b694-462c-985d-e317ea602c36.png)

dall'immagine vedi che se seleziono quella in fondo (NS3_L106F) mi seleziona anche la prima in cima (Spike_R346K) e viceversa quando  deseleziono l'ultima mi deseleziona anche la prima.

Ecco il video: 

https://user-images.githubusercontent.com/11488353/149397035-9a2fe881-75f6-4107-8501-50693ac9a44f.mp4

Sto provando il docker con quella che credo sia la tua ultima versione:
commit d53d2aa3636292ed8aa1f9239a2df2ec0622ba66 (HEAD -> main, origin/main, origin/HEAD)
Author: LucaCilibrasi <37807618+LucaCilibrasi@users.noreply.github.com>
Date:   Mon Jan 10 17:05:03 2022 +0100

**Comment by LucaCilibrasi** [comment]
Nuovamente non sono riuscito a replicare l'errore, probabilmente sbaglio qualcosa senza accorgermene. Ho provato comunque a fare delle modifiche, fammi sapere se l'errore continua ad esserci.

**Comment by sunbrn** [comment]
Adesso che funziona bene il "deselect all" mi sembra che non ci sia più questo problema
