### ISSUE TITLE
Rendere più comprensibile il log della consolle

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#10]
ANNA: Idea: è possibile dare nel log del docker un'idea di massima dell'avanzamento di un 1. caricamento; 2. query di analisi? Tipo una percentuale di sequenze già caricate (1) e percentuale di mut processate rispetto a tutte le mutazioni da guardare (nel secondo caso)

LUCA: Forse possono essere fattibili queste cose. Scrivendo molto sulla console però non so quanto venga "capibile", proverò.

ANNA: ma non serve tanto, ad esempio ieri ho lanciato UK su 4 settimane che ci ha messo ovviamente molto. Già delle righe di questo tipo
![image](https://user-images.githubusercontent.com/11488353/149401527-9aa8cf84-3a99-46d9-aab8-5a26bf35bbf9.png)

mi aiutavano a capire l'avanzamento perché vedevo a quale delle 4 settimane era arrivato. Però il nome della mutazione non dice niente perché non so quante sono/in che ordine vengono processate, quindi si potrebbe aggiungere qui di fianco, per dire 5/100 mutation per dire che è arrivato alla quinta su cento.

**Comment by LucaCilibrasi** [comment]
Fatto

**Comment by sunbrn** [comment]
molto meglio!
