### ISSUE TITLE
Nice to have: additional mode with barplots of counts of sequences per week per location

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#14]
Sometimes it is difficult (without actually seeing data counts) to have an idea of which final date is most suitable as a "last date of the period".
An exploratory mode (static page with some barplots on available data in the country distributed by collection date -- grouped by week) would be very useful

**Comment by lucagrammer** [comment]
Added in 344d434dc71ac1b519e1e43516744dd8a0b5d4b7
