### ISSUE TITLE
Backend: ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#16]
Backend problem.

I loaded the 2022-02-15 database with LOCATION='United Kingdom'

Query on Lineage Independent mode:
country = United Kingdom, 
date = 2022-02-13

I get this error on the console:

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/11488353/154432626-f35e31a0-8227-4bc2-aebe-8f91a15ec85f.png">

**Comment by lucagrammer** [comment]
Fixed in commit 19c5eb155d34021df1aba9849c55ffa97c6707e2

**Datails**: The problem was related to the fact that some rows in the dataset do not have information about the mutation.
Now the APIs perform additional checks to avoid exceptions and discard these lines from the results.
