### ISSUE TITLE
Heatmaps with more rows, as selected by the user

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#17]
Now the heatmap shows the first five and the last five of any list of mutations that I select on the table

For example, here, I selected 15 mutations sorted by desc slope
and I see in the heatmap the last 5 mutations of the table (sorted bottom up in the table, but top-down in the heatmap) and the first 5 mutations of the table (sorted top-down in the table, but bottom-up in the heatmap). 

<img width="552" alt="image" src="https://user-images.githubusercontent.com/11488353/154751473-08d95d07-2048-4bf7-9914-dd58d9ba7eba.png">

I think it would be better to allow a larger number of rows (50?) in the heatmap and, if possible, to sort its rows in the same way as they are sorted in the table.

**Comment by acanakoglu** [comment]
Resolved in the commit (https://github.com/DEIB-GECO/VariantHunter/commit/9b1b573a9ff99d64d4dad1f632501ba53c78f4e4)

The order is not as described; the order is always by the default order of (Step)
