### ISSUE TITLE
Show the absolute number of mutations (not just the prevalence) in the heatmap cells

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#19]
In the heatmap, it would be useful to show in the label of each cell, for Z, not only the percentage, but also the absolute value. 
For making it more direct, if possible, it could be shown directly in the cell instead of having to hover on it.

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/11488353/154804849-44e06098-3136-480b-8f47-2a41ffcd949d.png">

**Comment by lucagrammer** [comment]
Added in commits 9f562d13d188bec9982d2db74595a08d83c0f574 and ae9acafd456a9d49f25b2d7a7008c56304408ff1
