### ISSUE TITLE
Nice to have: in Mode Lineage-dependent

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#2]
Dal punto dell'utilizzatore,  nella tabella, sarebbe meglio lasciare anche le colonne sulle prevalenze dei 4 periodi. Almeno per quando si scarica la tabella (ma credo tcosti poco lasciarle anche a dx dei p-value, magari con uno switch per aggiungerle toglierle?)

Nella heatmap adesso con hovering non si vede nulla, si può ripristinare la visualizzazione di un cartellino con il numero di seq assoluto / tot?

![image](https://user-images.githubusercontent.com/11488353/149392209-aa9c20f3-6977-43ee-b78f-cbc0ba2d0910.png)

**Comment by LucaCilibrasi** [comment]
Fatto
