### ISSUE TITLE
Nice to have: function to "print a report", i.e., taking as screenshot of the entire page

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#21]
I think Andrea Gulino had done something like this for VirusViz (like a button that calls the print-page function of the browser)

**Comment by lucagrammer** [comment]
Added in ed651e491a9a9a4ccf4d20f81af9c4fd3a20290e commit.

Now it's possible to: 
- download the data of the table (download data)
- download a screenshot of the current view (download all)
<img width="582" alt="Schermata 2022-03-05 alle 19 12 51" src="https://user-images.githubusercontent.com/50906588/156895312-bf810b31-d2f7-4bd4-b6c3-89e3d1842244.png">
The downloaded image will be something like this:
<img width="582" alt="Schermata 2022-03-05 alle 19 12 51" src="https://user-images.githubusercontent.com/50906588/156895490-fb44174c-bb1b-49a0-af4b-f54ed0bd2342.png">
