### ISSUE TITLE
Make order of rows in the table reflected in the heatmap

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#25]
Even after applying particular sorting on the table columns, it would be nice to have it reflected on the heatmap, so this can be easier to be analyzed and communicate more efficiently the mutations' clusters trends

**Comment by lucagrammer** [comment]
Previously the sorting algorithm did not work and the sorting of the data in the heatmap was not in sync. This problem has been corrected in the f457a13022c0b72d247a1dcdb51d4cdb6a5abaec commit
