### ISSUE TITLE
Nice to Have: Dashed lines in the lineplot for mutations with few points

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#27]
To visually support the analysis of countries with few observations, it could be useful to differentiate the lines using a diferent style (dashed?) to indicate visually that there are few sequences and thus the trends should be considered carefully

**Comment by lucagrammer** [comment]
Please define what you mean by "few".
You mean: given a threshold X, use dashed lines when the data points are less than X. Or something else?

**Comment by sunbrn** [comment]
You are right, this comment is not a defined requirement. 
I try something more concrete. In order to make this graph more informative you could add:

1.  The number of total collected sequences in a specific time point (maybe below the dates labels or above the graph?)
![image](https://user-images.githubusercontent.com/11488353/156670763-7e5a775d-5b12-48c4-aec6-260344f2b234.png)

1. Use a different simbol (instead of circle, a cross) in those observations that have less than 5 mutations
![image](https://user-images.githubusercontent.com/11488353/156670951-c767e543-cc52-4d41-813e-da07e53a3a23.png)

1. If all the four observations of a mutations are below  a count of 5, make the whole line dashed
![image](https://user-images.githubusercontent.com/11488353/156671246-e67cbf19-4114-4d4a-a006-5c13091d5c13.png)

1. Reformat the labels of each point, on hovering, as suggested in this image: name of mutation, absolute number of mutations in that week, percentage (= absolute number/tot. of the week). The total of the week can be read below or above the graph, as we said in point 1.
![image](https://user-images.githubusercontent.com/11488353/156671432-94333338-02bd-4458-8ebd-9a6432441373.png)

**Comment by lucagrammer** [comment]
Added in commit ae9acafd456a9d49f25b2d7a7008c56304408ff1

<img width="1161" alt="Schermata 2022-03-06 alle 16 16 51" src="https://user-images.githubusercontent.com/50906588/156930741-f7592cd1-aa9b-4f22-a33c-296eb8449d79.png">
