### ISSUE TITLE
Add dates + collected samples, to the column names "0-7 days before"

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#29]
In the table, heatmap and lineplot columns, it would be better to add also the dates (instead of just "X-Y days before") so it is clearer for the user.

It would also be useful to give, for each week, the total number of collected sequences in that location.

Note: Shay's suggestion

**Comment by lucagrammer** [comment]
Adding too long text (_yyyy/mm/dd - yyyy/mm/dd   X-Y days before_) in the table, heatmap and lineplot causes unclear layouts  for the whole table and for both charts which make them difficult to read.

**Proposed solution (implemented from d0770021fd01bd0cb609d975c0d70143ec608558 commit ):** replace the headings and references to time periods with the dates themselves (_yyyy/mm/dd - yyyy/mm/dd_). See attached screenshots. 

Please, close the issue if the solution is satisfactory.

<img width="1092" alt="Schermata 2022-03-04 alle 00 01 19" src="https://user-images.githubusercontent.com/50906588/156667380-aebc075c-c456-41a5-ba9f-f794dcf3cb24.png">

<img width="1092" alt="Schermata 2022-03-04 alle 00 00 02" src="https://user-images.githubusercontent.com/50906588/156667244-cf58f773-2b29-49d4-affb-55fc098655e5.png">

<img width="1092" alt="Schermata 2022-03-04 alle 00 00 14" src="https://user-images.githubusercontent.com/50906588/156667258-d1eb4718-bb7a-4e17-8a33-abf95fb1f28a.png">

**Comment by sunbrn** [comment]
perfect!
