### ISSUE TITLE
P-value in Lineag-indep?

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#3]
Nel Mode 'Lineage-indep' sono rimasti i p-value (c'è un switch button per aggiungerli) ma cosa vogliono dire qui che non c'è il lineage? Anche la info table headers contiene info sui p-value che non mi sembra abbiano senso. E' un refuso, giusto?

![image](https://user-images.githubusercontent.com/11488353/149392344-9c304a89-429d-495a-954a-e48ffd9c9930.png)

**Comment by LucaCilibrasi** [comment]
Avevo sbagliato la descrizione in "info table headers", ho tolto tutte le menzioni ai lineage. I p-value in teoria vanno bene anche per questa parte, solo non trattano i lineage. Ci dovrebbe essere la descrizione anche di questi p-value fatta da Pietro nel Readme del docker.
