### ISSUE TITLE
Error in analysis

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#30]
I did this analysis in the "Lineage Specific" mode
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/11488353/155742677-c995b5c6-d052-49c6-bc4d-388f10d19243.png">

and I get this error
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/11488353/155742972-d768b80e-6216-431f-949d-c44c54d0b356.png">

**Comment by lucagrammer** [comment]
HTTP error handling has been added since 34274e417edb3e15c708b65beb38899574e36bc2 commit. 
By reproducing the steps described above, the problem no longer arises.

**Comment by sunbrn** [comment]
Sorry, I forgot to specify that, when the error occurred, the used dataset was metadata.tsv of the 2022-02-22.
If you tested it with a more updated metadata.tsv file, it could be that the error does not happen because there is more data for that period. 
Could you please check which dataset you tested the steps with?

**Comment by lucagrammer** [comment]
I used exactly that dataset (metadata.tsv of the 2022-02-22)

**Comment by sunbrn** [comment]
ok thanks
