### ISSUE TITLE
Nice to have: filter table by mutation list

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#34]
Often I want to check in the table if a list of mutations (typical of a new variant) are there or not. 
I now do it using CTRL+F on the browser, checking the present of mutations one by one. 
Could it be possible to have a field, comma separated, where, e.g., I write
"S:S477N,S:T478K,S:E484A,S:Q493R,S:D614G,S:H655Y"

and it filters only these mutations in the table?

**Comment by lucagrammer** [comment]
Maybe I can implement a more user-friendly filter like the one for proteins which allows to select multiple options.
What does it represent the value before the : ? Is it the protein?

**Comment by sunbrn** [comment]
yes, it is the protein. 
Then it would be "Spike" (not S)
Sorry I used a different notation.
Your proposal seem ok!

**Comment by lucagrammer** [comment]
Yes, I thought it was so.

By the way, the filter has been added in commit  4a55be94821e0867619e825d696668c8b5e04e89

<img width="1280" alt="Schermata 2022-03-09 alle 15 18 09" src="https://user-images.githubusercontent.com/50906588/157459631-18b0015f-5e44-4ea2-a975-4124e0273f91.png">
