### ISSUE TITLE
Nice to have: next period button

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#35]
Suppose I am doing an analysis for
Country, Italy, 2022-02-28

Would it be possible to have a button that allows to automatically create another analysis (another panel) for the next/previous weekly period?

-> Country, Italy, 2022-02-21
-> Country, Italy, 2022-03-07

just by adding/subtracting 7 days from the date

**Comment by lucagrammer** [comment]
Added in f0195214288e9b14bb52363508e5486f200ebd32

<img width="729" alt="Schermata 2022-03-09 alle 13 34 54" src="https://user-images.githubusercontent.com/50906588/157442869-a3a0ab4b-c6af-4567-aac8-921f31b0f99d.png">
