### ISSUE TITLE
Divisione per zero

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#5]
Problema divisione per zero (non ricordo se era nel Mode 1 o 2, credo 1)
settimana 2022-01-01
United Kingdom BA.2 Spike_N440K

Questo lo screenshot del log:
![image](https://user-images.githubusercontent.com/11488353/149392650-21071b30-8d62-46e9-ad00-fa37e9521c85.png)

LUCA: Ok, modifico il codice aggiungendo un controllo eventualmente.

**Comment by LucaCilibrasi** [comment]
Fatto
