### ISSUE TITLE
Cambiare numero etichette barplot

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#6]
Ma qui si era deciso di mettere #sequenze = numero assoluto di quelle con la mutazione o di ripetere per ogni mutazione il totale (qui 850, che però potrei guardare anche andando sopra il pallino della linea rossa sopra...)?

![image](https://user-images.githubusercontent.com/11488353/149400218-2fe00bd0-b217-4869-a757-c9099574c1cc.png)

LUCA: Si errore mio, ho messo il denominatore anziché il numeratore della frazione.

**Comment by LucaCilibrasi** [comment]
Fatto
