### ISSUE TITLE
Tabella da scaricare in Mode Lineage-indep

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#7]
Mi sono accorta che una riga della tabella che si può scaricare in csv, e.g.,
"South Africa","Spike","R346K","0","0.006578947368421052","0","0","0","0.01953125","0.03189493433395872","0.05058823529411765","0.030612244897959183","0.02702702702702703","0.021739130434782608","0.03508771929824561"
non è molto utile solo con le percentuali... sarebbe opportuno dare anche i totali delle sequenze. Per non modificare tutta la tabella, basterebbe aggiungere una riga in cima o in fondo con il totale per settimana.

LUCA: Ok, questo è fattibile.

**Comment by LucaCilibrasi** [comment]
Fatto
