### ISSUE TITLE
Nice to have (fantascienza?): un modo per stoppare le analisi quando si chiude il browser?

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#8]
Ho notato che, anche se la mia analisi è sull'India, 
vengono fuori linee con altri stati, e.g., UK e Germany. Che erano analisi che avevo fatto prima (nello stesso docker, ma in pagine del browser che poi ho chiuso...) Forse semplicemente chiudere il browser non fa stoppare le analisi?

LUCA: Se si chiude il browser le analisi non vengono stoppate, continuano ad andare finché raggiungono un risultato. Quindi quelle che vedevi potevano essere le precedenti analisi che ancora non erano terminate.

ANNA: Non c'è nessun modo per forzare lo stop delle analisi quando si chiude la finestra del browser vero? Perché se uno si è sbagliato o ha lanciato un'analisi troppo lunga... l'unico modo per stoppare tutto è stoppare anche il docker e ricreare il db da zero

**Comment by LucaCilibrasi** [comment]
Purtroppo non ho trovato un modo per forzare lo stop chiudendo il browser.

**Comment by sunbrn** [comment]
Magari dal browser è impossibile, ma invece direttamente dal terminale non si riesce a interagire con il docker che al momento è up e dirgli di stoppare quell'analisi?

**Comment by LucaCilibrasi** [comment]
Da prove che avevo fatto non mi sembrava possibile (o almeno facile) interagire con l'applicazione tramite terminale una volta avviato il docker. Inoltre, per stoppare una precisa analisi è necessario conoscere l'ID relativo a quella query, cosa che l'utente non può sapere (e che non viene salvata nemmeno nel programma). All'utente quindi non basta specificare i parametri della query per poterla cancellare.
