### ISSUE TITLE
Mode Lineage-indep: Permettere di vedere anche periodi "next" non pieni

### ISSUE THREAD

**Issue by sunbrn** [DEIB-GECO/VariantHunter#9]
Qui è un peccato non poter vedere la settimana dopo... dopo perché non ci sono altri 4 periodi... non si può avanzare solo di uno alla volta? Così poi potrei scaricarmi la tabella completa

![image](https://user-images.githubusercontent.com/11488353/149400892-495e68d2-ec47-4f12-8a69-4d8379dd5dc7.png)

LUCA: Per come mi salvo i dati aggiungere un periodo di 1 settimana quando tutti gli altri periodi sono di 4 mi creerebbe un po' un problema. L'unica cosa che posso fare è modificare la condizione sul tasto next. Ora questo tasto è disabilitato se la data di fine analisi (quindi delle 4 settimane successive) è maggiore della data di oggi. Posso fare che viene disabilitato se la data di fine analisi (quindi delle 4 settimane successive) è maggiore della data di oggi + 4 settimane. In questo modo si dà la possibilità di aggiungere un ulteriore periodo (di 4 settimane) di cui magari anche solo la prima settimana è piena coi dati, le altre no.

ANNA: va bene

**Comment by LucaCilibrasi** [comment]
Fatto
